### PR TITLE
feat: compatibility with doctrine orm 3.0 minimum

### PR DESCRIPTION
**Pull request by monpetitplacement**
This PR updates the extension to be compatible with Doctrine 3.0, which is now the minimum required version. I had to remove support for ArrayType and ObjectType, as they are no longer natively supported by Doctrine. 

All tests pass.

### CODE REVIEW

**Comment by Gwemox** [comment]
image

**Comment by Gwemox** [comment]
@x86demon can you rebase branch 3.x with master ?

**Comment by Gwemox** [comment]
> Hi @Gwemox. master mostly contains in-development features that are planned for next release. What functionality do you need in 3.x? Maybe I can cherry-pick some commits or adopt PR for 3.x?

Add CI?

**Comment by x86demon** [comment]
CI was ported to 2.x and 3.x

**Comment by Gwemox** [comment]
Up ? 👼

**Comment by x86demon** [comment]
Hi @Gwemox. Thank you for the PR
I'll put it in the queue for review and will do my best to review it in one of upcoming sprints.

**Comment by yakobe** [comment]
Would be great if this could get merged and released. It's the last compatibility blocker for me 😃

**Pull request merged**
