### PR TITLE
Remove usages of Doctrine Inflector

### LINKED ISSUE #71: Not working with Doctrine ORM 2.8
The Bundle use `Doctrine\Common\Inflector\Inflector::classify` that was deprecated since Doctrine ORM 2.7 and has been removed in Doctrine ORM 2.8.

This bundle is no longer working.

### PR DESCRIPTION
**Pull request by mbessolov**
This replaces #69 and fixes #71

### CODE REVIEW

**Comment by orocla** [comment]
Thank you for your pull request.

It looks like this may be your first contribution to an Oro, Inc. open source project, in which case you'll need to sign a Contributor License Agreement (CLA) at https://oroinc.com/b2b-ecommerce/contributor-license-agreement/

If you've already signed the CLA, it's possible we don't have your GitHub username or you're using a different email address. GitHub uses the email address you set in your local Git configuration to associate commits with your GitHub account. Please sign the CLA again using the correct GitHub username and email address or see this help article on [setting the email on your git commits](https://help.github.com/articles/setting-your-email-in-git/).

Once you've signed the CLA, please allow for some time for the submission to be processed.

**Comment by mbessolov** [comment]
I hope that Travis builds will pass on the latest commit - https://travis-ci.org/github/oroinc/doctrine-extensions/builds/750156088
PHP 7.3 is not tested because of #73 (can probably be achieved with dynamically replacing convertWarningsToExceptions in phpunit.xml, as this old version of phpunit 4.8.x does not even support --fail-on-warning option, at least until we upgrade the dev-dependencies/tests to work with doctrine/orm >2.6).

**Comment by mbessolov** [comment]
No luck getting anything other than 7.4.0 on Trusty on Travis.
For now we will go without Travis builds on 7.3 and 7.4. It will be fixed in #73

**Comment by mbessolov** [comment]
I've got the green light from @x86demon, so here it goes.
Tagging as 1.3.1 now.

**Pull request merged**
